### ISSUE TITLE
Activity 2 : Create an image and run the image of Pythonflask application

### ISSUE THREAD

**Issue by snehal-herovired** [snehal-herovired/LearningGIt#12]
All the steps must be done and screenshot must be provided in github branches.
give a detailed description in a text file of what you understood in the python flask application regarding the dockerfile and the application itself.

**Comment by NandaKishore777** [comment]
![2023-02-14](https://user-images.githubusercontent.com/81244648/218687014-b6e5293e-12c6-4505-89cf-f16c1297fe3d.png)
![2023-02-14 (1)](https://user-images.githubusercontent.com/81244648/218687028-67539841-53ed-413e-be63-f8e1173dc27c.png)

**Comment by Gangadhar-7** [comment]
[FlaskAPI_Activity.docx](https://github.com/snehal-herovired/LearningGIt/files/10730720/FlaskAPI_Activity.docx)

**Comment by Bandarlankasivadurga** [comment]
!pythonflask.png…]()

**Comment by Bandarlankasivadurga** [comment]
![pythonflask](https://user-images.githubusercontent.com/102519417/218692974-666d4dd8-9aff-46c2-bda4-96ef54b86b9b.png)

**Comment by Mani10101** [comment]
![python_flask](https://user-images.githubusercontent.com/106660208/218693192-526257d4-92f6-41be-a351-5f8caa62bb6a.png)

**Comment by Abhinand-ECE** [comment]
Assignment 2
<img width="960" alt="2023-02-14 (3)" src="https://user-images.githubusercontent.com/84446746/218696186-043340b7-4870-4eb1-bb17-e381dea7a6a5.png">
<img width="960" alt="2023-02-14" src="https://user-images.githubusercontent.com/84446746/218696201-aac05e6e-7d53-41a0-9232-65e264aadbb6.png">
<img width="960" alt="2023-02-14 (2)" src="https://user-images.githubusercontent.com/84446746/218696207-0785ecd4-c55c-419c-ae4b-00a1e54767e9.png">

**Comment by gokarakondaswamy** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/106660146/218696279-812c8de9-b86b-4baf-8ff5-21d9e86a31e9.png)

**Comment by gokarakondaswamy** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/106660146/218696495-5e19f19c-67c5-45e9-97c7-f3a2f023fe3d.png)

**Comment by Abhinand-ECE** [comment]
Assignment 2
<img width="960" alt="2023-02-14 (2)" src="https://user-images.githubusercontent.com/84446746/218696717-c9f9edef-b5ec-4803-9077-18fc9dd699dd.png">
<img width="960" alt="2023-02-14 (3)" src="https://user-images.githubusercontent.com/84446746/218696727-a6310092-51b7-49d2-be4b-fb06a779c949.png">
<img width="960" alt="2023-02-14 (1)" src="https://user-images.githubusercontent.com/84446746/218696733-d944b9e7-c038-4c6d-a2b3-3ab1e0d0183c.png">

**Comment by Deepika-Gutti** [comment]
![Screenshot (46)](https://user-images.githubusercontent.com/84383398/218697696-c88c27fa-2522-4fa8-9517-da6b8a521a97.png)
![Screenshot (45)](https://user-images.githubusercontent.com/84383398/218697727-0de9321d-18ad-4018-927e-24ea8401ccc1.png)

**Comment by Sandhya-Akula** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/84383268/218699236-bfcd7751-0700-4945-85be-b9d81e3927ae.png)
![Screenshot (41)](https://user-images.githubusercontent.com/84383268/218699297-327c9c2f-17c0-41a1-bd0a-2cbcab84ae01.png)

**Comment by Arepallibangarraju** [comment]
![Screenshot (115)](https://user-images.githubusercontent.com/84339229/218702190-61bcaf8f-c714-40ac-b6f5-07942a23318b.png)
![Screenshot (116)](https://user-images.githubusercontent.com/84339229/218702265-28b7c04d-f61e-47d0-8861-4b21cecb19ff.png)
![Screenshot (113)](https://user-images.githubusercontent.com/84339229/218702297-6eeb26c9-46d8-444c-b192-b824c43bc08f.png)

**Comment by siva9800** [comment]
![Screenshot (163)](https://user-images.githubusercontent.com/106661571/218703582-b3dfd2a1-8f40-49e0-b9f1-23c36de0626c.png)
![Screenshot (164)](https://user-images.githubusercontent.com/106661571/218703598-8cae700f-1697-4e46-b248-b4f8182900a3.png)
![Screenshot (165)](https://user-images.githubusercontent.com/106661571/218703616-0043ed34-ac57-4380-a401-494f3ebc09aa.png)
![Screenshot (166)](https://user-images.githubusercontent.com/106661571/218703627-33192528-bc28-4a14-9d48-be5d88082950.png)

**Comment by DurgaRao441** [comment]
![Screenshot (79)](https://user-images.githubusercontent.com/84668549/218703823-22b4f942-863f-4e4b-be35-d52bc06d046c.png)
![Screenshot (76)](https://user-images.githubusercontent.com/84668549/218703853-367aef43-4980-46e1-9bad-82c74f6d33cd.png)

![Screenshot (77)](https://use![Screenshot (78)](https://user-images.githubusercontent.com/84668549/218703783-58cef73b-8c11-4f6a-b3be-be0473dac7a0.png)

**Comment by 21a95a0423** [comment]
![Screenshot (92)](https://user-images.githubusercontent.com/109517870/218704009-01ff12b5-3804-4ff0-8532-6e520ec63063.png)
![Screenshot (94)](https://user-images.githubusercontent.com/109517870/218704024-4be4449c-e0fb-4736-9d80-3df357b7fb85.png)

**Comment by Neelima8416** [comment]
<img width="1080" alt="docker1" src="https://user-images.githubusercontent.com/102217876/218704341-43506930-7cb0-49d7-bbfd-c34cd25296ac.png">
<img width="1080" alt="docker2" src="https://user-images.githubusercontent.com/102217876/218704372-25a32017-9d8b-41dd-83b1-2845d08e91d0.png">

**Comment by bsrtej** [comment]
<img width="960" alt="2023-02-14 (2)" src="https://user-images.githubusercontent.com/123041005/218704499-348ec83b-0100-48bb-a621-18ed75be2401.png">

**Comment by bsrtej** [comment]
<img width="960" alt="2023-02-14 (2)" src="https://user-images.githubusercontent.com/123041005/218704924-9427d9c9-c55a-4850-8152-ba12ed3ab253.png">
<img width="960" alt="2023-02-14 (3)" src="https://user-images.githubusercontent.com/123041005/218704935-5e2135e6-5d37-4449-8d73-e527c364ccea.png">

**Comment by karedlavijaya** [comment]
![2023-02-14](https://user-images.githubusercontent.com/102217877/218705326-d3622008-dd18-4386-9321-d7ecb3fe741a.png)

**Comment by karedlavijaya** [comment]
![2023-02-14](https://user-images.githubusercontent.com/102217877/218705492-bb91ceb7-4991-4738-a9f6-36c60c2abd71.png)
![2023-02-14 (1)](https://user-images.githubusercontent.com/102217877/218705549-4a5516d4-7d80-4a5d-8da3-04c79b43e4fd.png)
![2023-02-14 (2)](https://user-images.githubusercontent.com/102217877/218705592-e3ac47de-0a27-44c2-9fcb-19a09ba6586e.png)
![2023-02-14 (3)](https://user-images.githubusercontent.com/102217877/218705647-c2824112-dcec-4612-8fdc-ad3639542d94.png)

**Comment by sidda-chitti** [comment]
![Screenshot (264)](https://user-images.githubusercontent.com/84486145/218705868-51ede44f-87d4-4d5e-8d40-c4707fe90183.png)
![Screenshot (266)](https://user-images.githubusercontent.com/84486145/218705904-f8eeec55-e917-4503-aec2-a92158547a46.png)

**Comment by rameshthotakura** [comment]
![Screenshot (71)](https://user-images.githubusercontent.com/102218563/218706038-629b5761-577c-48e1-91b1-d5a212cf5808.png)
![Screenshot (72)](https://user-images.githubusercontent.com/102218563/218706059-bcc9a3a9-e395-4b97-8523-e2ed083d54c9.png)
![Screenshot (70)](https://user-images.githubusercontent.com/102218563/218706067-b518a12f-ed36-48c5-af96-b461f58facf5.png)

**Comment by deepika200326** [comment]
[activity2.pdf](https://github.com/snehal-herovired/LearningGIt/files/10731397/activity2.pdf)

**Comment by lakshmi-ummidi** [comment]
[HV Task 4C0.pdf](https://github.com/snehal-herovired/LearningGIt/files/10731342/HV.Task.4C0.pdf)

**Comment by 20A91A04J4** [comment]
![Screenshot (96)](https://user-images.githubusercontent.com/84438165/218709737-9eddf906-a3aa-4062-99db-bae0bda4a7ff.png)
![Screenshot (99)](https://user-images.githubusercontent.com/84438165/218710350-5b6b863d-1fe7-48c8-b5e5-d65dfc8fec9b.png)
![Screenshot (97)](https://user-images.githubusercontent.com/84438165/218710587-418e8287-d0f8-4285-8623-5384590f8804.png)

**Comment by Ankitha12345** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/84385353/218711493-0bc120ce-20b0-4c24-bed1-76a5d9b4df5f.png)
![Screenshot (2)](https://user-images.githubusercontent.com/84385353/218711550-5d7b2fc5-5df0-467b-87a0-aac3ce89cb0e.png)

**Comment by GondiJhansi** [comment]
![build_run_image](https://user-images.githubusercontent.com/84505647/218711651-fe1824a3-6773-49ca-a77e-0334eda5ea92.png)

**Comment by GondiJhansi** [comment]
![container_running](https://user-images.githubusercontent.com/84505647/218711771-cb72927a-cac4-4620-9794-a4dcf35f7af1.png)

**Comment by Saikrishna4468** [comment]
![herovired_Task](https://user-images.githubusercontent.com/102219617/219312736-8ed3d7a0-8d3e-4805-9b49-b2683e3fe141.jpg)

**Comment by 20A91A0435** [comment]
<img width="960" alt="2023-02-16" src="https://user-images.githubusercontent.com/84431531/219341552-9a56bdf0-43f4-4a09-87d8-381a45daf22e.png">
![Uploading 2023-02-16 (1).png…]()

**Comment by 20A91A0435** [comment]
<img width="960" alt="2023-02-16 (2)" src="https://user-images.githubusercontent.com/84431531/219341612-521fdfd2-b88d-4deb-87c4-6cac5fefc86b.png">
<img width="960" alt="2023-02-16" src="https://user-images.githubusercontent.com/84431531/219341676-d93fadc9-489b-4c6a-bb5d-d6189ce15713.png">
