### ISSUE TITLE
RESEARCH on what is DOCKERCOMPOSE in detail ? And also state the usage of .yaml or.yml file

### ISSUE THREAD

**Issue by snehal-herovired** [snehal-herovired/LearningGIt#17]

**Comment by 20A91A04D3** [comment]
Docker Compose is used for running multiple containers as a single service.
Benifits of Docker Compose:
1)Single host Deployment
2)Quick and easy configuration
3)Security
using .yaml and .yml we are able to Quick and easy co nfiguration which is one of the benifit of Docker compose

**Comment by 20a91a04e1** [comment]
"The Compose is a tool for defining and running multi-container Docker applications." 
With Compose, you use a YAML file to configure your application’s services. 
Then, with a single command, you create and start all the services from your configuration.

there are several types of command to execute like convert, build, create, down etc..

Using Compose is basically a three-step process:
1. Define your app’s environment with a Dockerfile so it can be reproduced anywhere.

2. Define the services that make up your app in docker-compose.yml so they can be run together in an isolated environment.

3. Run docker-compose up and Compose starts and runs your entire app.

common use cases:
Compose works in all environments: production, staging, development, testing, as well as CI workflows.

**Comment by Kumar1199** [comment]
Docker Compose is used for configuring and starting multiple Docker containers on the same host means don't have to start each container separately. The Dockerfile is used to build images while the dockercompose.yaml file is used to run images.

**Comment by 20A91A04D1** [comment]
Docker Compose is used for running multi-containers by using single command.
Benefits of Docker Compose:
Single host deployment - which means every application can run on single hardware
Quick and easy configuration - 
High productivity - which means it reduces time while performing task
Security - All the containers are isolated from each other
.yaml file is used to configure applications while .yml file is used to define services.

**Comment by kalpanamaddipatla** [comment]
DOCKER COMPOSE-an application to create **multiple containers** running in different services .
Any data or structure added to an XML or JSON file can also be stored in YAML. Users can write code for reading and generating YAML in any programming language. The extensions in YAML are .yaml and .yml. Both extensions stand for the same file type. YAML has several features that make it an excellent option for data formatting.
### USES OF DOCKER COMPOSE:
1)Automated testing environments-Developers can define and configure the environment needed for running automated end-to-end testing using the appropriate Docker Compose file.
2)Single host deployments

**Comment by 21P35A0347** [comment]
Docker compose is used to run multiple containers as a single service.you could create a file which would start both the containers as a service without the need to start each one separately .
YAML is the file to configure your application’s services. Then, with a single command, you create and start all the services from your configuration. 
Compose works in all environments: production, staging, development, testing, as well as CI workflows.

Benefits of Docker compose
• Single host deployment - This means you can run everything on a single piece of hardware
• Quick and easy configuration - Due to YAML scripts
• High productivity - Docker Compose reduces the time it takes to perform tasks
• Security - All the containers are isolated from each other, reducing the threat landscape
Basic Command of Docker Compose
• Start all services: Docker Compose up
• Stop all services: Docker Compose down
• Install Docker Compose using pip: pip install -U Docker-compose
• Check the version of Docker Compose: Docker-compose-v
• Run Docker Compose file: Docker-compose up -d
• List the entire process: Docker ps
• Scale a service - Docker Compose up -d -scale
• Use YAML files to configure application services - Docker Compose.yml

**Comment by deepika200326** [comment]
Docker Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application’s services. Then, with a single command, you create and start all the services from your configuration.
Compose works in all environments: production, staging, development, testing, as well as CI workflows. It also has commands for managing the whole lifecycle of your application:
Start, stop, and rebuild services
View the status of running services
Stream the log output of running services
Run a one-off command on a service

A docker-compose file is a YAML file that allows us to deploy multiples Docker containers at the same time.

A docker-compose.yml is a config file for [Docker Compose](https://docs.docker.com/compose/).

It allows to deploy, combine, and configure multiple docker containers at the same time. The Docker "rule" is to outsource every single process to its own Docker container.

**Comment by Ankitha12345** [comment]
Docker Compose : 
"Docker" is an open-source platform that makes development, shipping and deployment of application easy. It packages all the dependencies of an application in a so called container and runs it as an isolated environment. 
"Compose" is a tool for defining and running multi-container Docker applications. Compose works in all environments like production, staging, development, testing, as well as CI workflows. It also has commands for managing the whole lifecycle of your application.
Key Features Of Docker Compose:
- Have multiple isolated environments on a single host
- Preserves volume data when containers are created
- Only recreate containers that have changed
- Supports variables and moving a composition between environments
Usage Of .yaml or .yml File
With docker compose we use a single YAML file for every configuration and just single commands to start and stop all the services. If you are using a custom image then you will need to define its configurations in a separate docker file in contrast to using a prebuilt image from Docker Hub, which you can define with the docker compose .yaml file.

**Comment by lakshmi-ummidi** [comment]
Docker Compose is a tool that assists in defining and sharing multi-container applications. By using Compose, we can define the services in a YAML file, as well as spin them up and tear them down with one single command. Docker Compose is used for running multiple containers as a single service. Each of the containers here run in isolation but can interact with each other when required.
.yml file allows you to configure and document all your application's service dependencies (other services, cache, databases, queues, etc.). Using the docker-compose CLI command, you can create and start one or more containers for each dependency with a single command (docker-compose up).
The Compose file is a YAML file defining services, networks and volumes. The default path for a Compose file is ./docker-compose.yml.
Main Features of Docker Compose
Only recreate containers that have changed.
Have multiple isolated environments on a single host.
Preserves volume data when containers are created.
Supports variables and moving a composition between environments.

**Comment by prasannachowdary12** [comment]
DOCKER COMPOSE:

It is a tool that was developed to help define and share multiple container applications.
We can create YAML file to define the services and with a single command.
By using compose is we can define our application stack in a file, keep it at the root of our project repo.
we could create one file which would start both containers as a service without the need to start Each one  Seperately.
USAGE OF DOCKER COMPOSE:
Define the application dependencies.
Create a docker file.
Define services in a  compose file.
Build and run your app with Compose.
Edit the Compose file to add a bind mount.
Re-build and run the app with Compose.
Update the application.
USAGE OF YAML FILE:
 It  is optimized for data serialization, formatted dumping, configuration files, log files, and internet messaging and filtering.
Yaml allows you to represent complex data structures in a human-readable format. It is unambiguous. 
Yaml unambiguously specifies the data structures of the serialized data, so there's no need to rely on comments or documentation.
