### ISSUE TITLE
can any one resolve??

### ISSUE THREAD

**Issue by Nagendra180** [snehal-herovired/LearningGIt#23]
![Screenshot_20230219_200129](https://user-images.githubusercontent.com/106660151/219954718-5cd1581b-f73d-41ca-9251-7c15ef82623a.png)

**Comment by snehal-herovired** [comment]
Hi Nagendra.. 
follow this link https://stackoverflow.com/questions/68775869/message-support-for-password-authentication-was-removed-please-use-a-personal
and follow the steps and than access git
